import MisspassPage from '@/pages/personal/misspass/page';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Page() {
  return (
    <MisspassPage />
  )
}
