import MisspassPage from '@/windows/personal/misspass/page';

export const metadata = {
  title: 'SleepBag Спальники-Органайзеры: Забыл пароль',
  description: 'Generated by create next app',
}

export default function Page() {
  return (
    <MisspassPage />
  )
}
