import Image from 'next/image'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Page() {
  return (
    <main>
        <Image alt='Фоновое изображение' className='catalog_header_img aspect-video w-[100%] h-[110vh] object-cover' src='/bg/catalog_bg_img.png' width={1920} height={1080}/>
        <div className='container m-auto flex justify-center'>
            <div className='absolute w-[637px] h-[919px] bg-[#fff] translate-y-[-105%] z-0 opacity-50 rounded-3xl'></div>
            
            <div className='w-[591px] h-[873px] bg-[#fff] p-[48px] translate-y-[-108%] absolute z-1 rounded-3xl shadow-2xl'>
                
                <div className='auth_header items-start flex flex-col'>
                    
                    <h1 className='items-start font-bold m-[0px] font-[Unbounded] text-4xl'>Подтверждение личности</h1>
                    
                    <div className='mt-[34px] text-left text-base'>
                        <p className='m-[0px] text-gray-600'>Введите код, который мы отправили на адрес <span className='text-black'>ПОЧТА ПОЛЬЗОВАТЕЛЯ</span></p>
                    </div>
                
                </div>
                
                <hr className='mt-[35px] mb-[35px] bg-[#000]'/>
                
                <div className='main_auth'>
                    
                    <form className='flex flex-col' action='/proof_code' method='post'>
                        
                        <div className='flex flex-row gap-[15px]'>
                          <input className='w-[15%] h-[89px] pl-[17px] rounded-xl focus:outline-orange-500 border-[1px] border-gray-500 text-5xl'></input>  
                          <input className='w-[15%] h-[89px] pl-[17px] rounded-xl focus:outline-orange-500 border-[1px] border-gray-500 text-5xl'></input>  
                          <input className='w-[15%] h-[89px] pl-[17px] rounded-xl focus:outline-orange-500 border-[1px] border-gray-500 text-5xl'></input>  
                          <input className='w-[15%] h-[89px] pl-[17px] rounded-xl focus:outline-orange-500 border-[1px] border-gray-500 text-5xl'></input>  
                          <input className='w-[15%] h-[89px] pl-[17px] rounded-xl focus:outline-orange-500 border-[1px] border-gray-500 text-5xl'></input>  
                          <input className='w-[15%] h-[89px] pl-[17px] rounded-xl focus:outline-orange-500 border-[1px] border-gray-500 text-5xl'></input>  
                          <input className='w-[15%] h-[89px] pl-[17px] rounded-xl focus:outline-orange-500 border-[1px] border-gray-500 text-5xl'></input>  
                        </div>

                        <div className='flex flex-row justify-end gap-[50px]'>
                            <a href='/forgot_password' className='text-right font-semibold text-[#f97316] pt-[15px]'>Назад</a>
                            <a href='#' className='text-right font-semibold text-[#f97316] pt-[15px]'>Отправить код повторно</a>
                        </div>
                    
                    </form>
  
                </div>
  
            </div>
        </div>
    </main>
  )
}
