import PurchasesPage from "@/windows/personal/purchases/page";

export const metadata = {
    title: 'SleepBag Спальники-Органайзеры: Покупки',
    description: 'Generated by create next app',
  }

export default function page() {
    return (
        <PurchasesPage />
    );
}