import OrdersPage from "@/windows/personal/orders/page"

export const metadata = {
    title: 'SleepBag Спальники-Органайзеры: Оформление заказа',
    description: 'Generated by create next app',
}

export default function Page() {
    return (
        <OrdersPage /> 
    )
}