import ContactsPage from "@/pages/contacts/page"

export const metadata = {
  title: 'SleepBag Спальники-Органайзеры: Контакты',
  description: 'Generated by create next app',
}

export default function Page() {
    return (
      <ContactsPage />
    )
}
