import OrderPage from "@/pages/personal/cart/order/page"

export const metadata = {
  title: 'SleepBag Спальники-Органайзеры: Оформление заказа',
  description: 'Generated by create next app',
}

export default function Page() {
  return (
    <OrderPage />
  )
}
