import OrderAccessPage from "@/windows/personal/cart/order/access/page"

export const metadata = {
  title: 'SleepBag Спальники-Органайзеры: Заказ подтверждён',
  description: 'Generated by create next app',
}

export default function Page() {
  return (
    <OrderAccessPage />
  )
}
