import AuthPage from '@/pages/personal/auth/page';

export const metadata = {
  title: 'SleepBag Спальники-Органайзеры: Авторизация',
  description: 'Generated by create next app',
}

export default async function Page() {
    return (
        <AuthPage />
    )
}
