import Image from 'next/image'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Page() {
  return (
    <main className="container m-auto">
        <article className='link_path translate-y-[10vh]'>Главная / <span>Личный кабинет</span></article>
        <section className='userpage_info'>
            <div className='info_left'>
                <Image src="/images/user_photo.png" alt='Фото пользователя' width={488} height={488} className="rounded"></Image>
            </div>
            <div className='info_right'>
                <hr/>
                <div></div>
                <hr/>
                <div></div>
                <hr/>
                <div></div>
                <hr/>
                <div></div>
                <hr/>
            </div>
        </section>
        <section className='userpage_blocks'>

        </section>
    </main>
  )
}
