import RegPage from '@/pages/personal/reg/page';

export const metadata = {
  title: 'SleepBag Спальники-Органайзеры: Регистрация',
  description: 'Generated by create next app',
}

export default function Page() {
  return (
    <RegPage />
  )
}
