import OrdersIdPage from "@/pages/personal/orders/[id]/page";

export const metadata = {
    title: 'SleepBag Спальники-Органайзеры: Информация о заказе',
    description: 'Generated by create next app',
  }

export default function page({params}) {
    return(
        <OrdersIdPage params={params} />
    )
}