import Catalog from '@/components/Index-page/catalog'
import productSwiper from '@/components/catalog/slug/slider'
import { getProductSlug } from '@/services/catalog/page'
import { cookies } from 'next/headers'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function Page({params}) {
    const cookieStore = cookies()
    const userJWT = cookieStore.get('userJWT')

    const productData = await getProductSlug(params.slug)

    return (
        <main className="container m-auto">
            <article className='link_path pt-[13vh]'><a href='/' className='text-[#000] opacity-70'>Главная / </a><a href='/catalog' className='text-[#000] opacity-70'>Каталог / </a><span>productData.data_NAME</span></article>

            <section className='productData.data_card flex flex-row'>
                <div className='w-[50%]'>
                    <productSwiper />           
                </div>

                <div className='w-[50%]'>
                    <div className='flex flex-col gap-[20px] pb-[20px]'>
                        <h2 className='font-bold text-[30px]'>{productData.data[0].attributes.name}</h2>
                        <p className='text-[32px] font-[600] text-[#f97316]'>{productData.data[0].attributes.price}₽</p>
                        <p className='text-[20px] text-[#8d8d8d]'>{productData.data[0].attributes.description}</p>
                    </div>
                    {/* <div className='flex flex-col gap-[12px] pb-[20px]'>
                        <h3 className='text-[#000] text-[20px] font-[600] underline'>ЦВЕТ</h3>
                        <div className='catalog_object_buttons flex gap-[20px]'>
                            <button className='text-[20px] text-[#8d8d8d]'>Оранжевый</button>
                            <button className='text-[20px] text-[#8d8d8d]'>Зелёный</button>
                            <button className='text-[20px] text-[#8d8d8d]'>Синий</button>
                            <button className='text-[20px] text-[#8d8d8d]'>Чёрный</button>
                        </div>
                    </div>
                    <div className='flex flex-col gap-[12px] text-[20px] font-[600] pb-[20px]'>
                        <h3 className='text-[#000] underline'>РАЗМЕР</h3>
                        <div className='catalog_object_buttons flex gap-[20px]'>
                            <button className='text-[#8d8d8d] font-[400]'>XL</button>
                            <button className='text-[#8d8d8d] font-[400]'>L</button>
                            <button className='text-[#8d8d8d] font-[400]'>M</button>
                            <button className='text-[#8d8d8d] font-[400]'>S</button>
                        </div>
                    </div> */}
                    <div className='flex flex-col pb-[20px] gap-[12px]'>
                        <p>{productData.data[0].attributes.count} шт. в наличии</p>
                        <div className='flex flex-row gap-[6px]'>
                            <button className='bg-[#e6e9ec] items-center justify-center aspect-square w-[7%]'>-</button>
                            <input className='border-solid border-[1px] border-[#e6e9ec] w-[13%] text-center' value={1}></input>
                            <button className='bg-[#e6e9ec] items-center justify-center aspect-square w-[7%]'>+</button>
                        </div>
                    </div>
                    <div className='productData.data_buttons flex flex-row items-center pb-[20px] gap-[15px]'>
                        <button className='rounded-[10px] bg-[#f97316] w-[35%] h-[56px] text-[#fff] text-[18px] items-center justify-center tracking-widest'>Добавить в корзину</button>
                        <button className='rounded-[10px] border-solid border-[#000] border-[1px] tracking-widest w-[35%] h-[56px] text-[18px] items-center justify-center'>Купить сейчас</button>

                        {userJWT != undefined ? (
                            <div className='add_favorite flex flex-row gap-[17px]'>
                                <svg width="24" height="21" viewBox="0 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M1 8.625C1 4.04167 4.64583 3 6.72917 3C9.33333 3 11.4167 5.08333 12.4583 6.64583C13.5 5.08333 15.5833 3 18.1875 3C20.2708 3 23.9167 4.04167 23.9167 8.625C23.9167 15.5 12.4583 21.75 12.4583 21.75C12.4583 21.75 1 15.5 1 8.625Z" stroke="#8d8d8d" stroke-width="1.5"/></svg>
                            </div>
                        ) : ('')}
                    </div>
                    
                    <p className='category_text text-[#8d8d8d]'>Категория: 
                        {productData.data[0].attributes.categories.data.map(category => 
                            " " + category.attributes.name + "."
                        )}
                    </p>
                </div>

            </section>

            <section className='next_info mb-[50px]'>
                <hr className='next_info_hr hidden mt-[20px] mb-[15px] h-[2px] bg-[#000] opacity-40'/>
                <div className='next_info_h3 flex flex-row text-[20px] gap-[60px]'>
                    <h3 className='text-[#f97316]'>ОПИСАНИЕ</h3>
                    <h3 className='additional'>ДОПОЛНИТЕЛЬНАЯ ИНФОРМАЦИЯ</h3>
                </div>
                <hr className='next_info_hr2 mt-[20px] mb-[15px] h-[2px] bg-[#000] opacity-40'/>
                <p>Характеристики товара:
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna viverra non, semper suscipit, posuere a, pede. Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis. Phasellus ultrices nulla quis nibh. Quisque a lectus. Donec consectetuer ligula vulputate sem tristique cursus. Donec consectetuer ligula vulputate sem tristique cursus.
                Ширина
                Длина
                Высота
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna viverra non, semper suscipit, posuere a, pede. Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis. Phasellus ultrices nulla quis nibh. Quisque a lectus. Donec consectetuer ligula vulputate sem tristique cursus.</p>
                <hr className='mt-[15px] mb-[15px] h-[2px] bg-[#000] opacity-40'/>
                <div className='add_info576 hidden'>
                    <h3>ДОПОЛНИТЕЛЬНАЯ ИНФОРМАЦИЯ</h3>
                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna viverra non, semper suscipit, posuere a, pede. Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis. Phasellus ultrices nulla quis nibh. Quisque a lectus. Donec consectetuer ligula vulputate sem tristique cursus. Donec consectetuer ligula vulputate sem tristique cursus.</p>
                    <hr className='mt-[15px] h-[2px] bg-[#000] opacity-40'/>
                </div>
            
            </section>
            
            <section className='similar'>
                    <h3 className='text-[20px] pb-[40px] font-[600]'>СМОТРИТЕ ТАКЖЕ</h3>

                    {/* <Catalog/> */}
            </section>

        </main>
    )
}
