import Image from 'next/image'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Page() {
  return (
    <main>
        <Image className='catalog_header_img aspect-video w-[100%] h-[100vh] object-cover' src='/bg/catalog_bg_img.png' width={1920} height={1080}/>
        <div className='container m-auto flex justify-center'>
            <div className='absolute w-[637px] h-[919px] bg-[#fff] translate-y-[-105%] z-0 opacity-50 rounded-3xl'></div>
            
            <div className='w-[591px] h-[873px] bg-[#fff] p-[48px] translate-y-[-108%] absolute z-1 rounded-3xl shadow-2xl'>
                
                <div className='auth_header items-end flex flex-row'>
                    
                    <h1 className='items-end font-bold m-[0px] font-[Unbounded] text-4xl'>Авторизация</h1>
                    
                    <div className='h-[80px] text-right text-base'>
                        <p className='m-[0px] text-gray-600'>У вас ещё нет аккаунта?</p>
                        <a className='m-[0px] text-[#f97316] font-semibold' href='/registration'>Зарегистрироваться</a>
                    </div>
                
                </div>
                
                <hr className='mt-[35px] mb-[35px] bg-[#000]'/>
                
                <div className='main_auth'>
                    
                    <form className='flex flex-col' action='/login' method='post'>
                        <label for='email' className='text-xl pb-[15px]'>Введите ваш адрес эл. почты</label>
                        <input type='email' className='w-[100%] h-[62px] focus:outline-orange-500 border-[1px] border-gray-500 text-xl pl-[27px] pb-[20px] pt-[20px] rounded-xl' placeholder='E-mail' id='email' name='email' required/>
                        <label for='password' className='text-xl pb-[15px] pt-[25px]'>Введите пароль</label>
                        <input type='password' className='pb-[25px] focus:outline-orange-500 flex justify-end w-[100%] h-[62px] border-[1px] border-gray-500 text-xl pl-[27px] pb-[20px] pt-[20px] rounded-xl' id='password' name='password' placeholder='********' required/>
                        <button type='submit' className='mt-[25px] flex justify-center items-center text-white bg-[#f97316] h-[62px] text-xl rounded-xl'>Авторизоваться</button>
                        <a href='/forgot_password' className='text-right font-semibold text-[#f97316] pt-[15px]'>Забыли пароль?</a>
                    </form>
  
                </div>
  
            </div>
        </div>
    </main>
  )
}
