import ReceiptsPage from "@/pages/personal/receipts/page";

export const metadata = {
    title: 'SleepBag Спальники-Органайзеры: Чеки',
    description: 'Generated by create next app',
  }

export default function page() {
    return (
        <ReceiptsPage />
    );
}