import Image from 'next/image'
import { getFAQ } from '@/services/IndexPage'
import FAQ from '@/components/faq'
import { getProducts } from '@/services/IndexPage'
import { LikeCatalog } from '@/components/like'
import Catalog from '@/components/Index-page/catalog'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function Page() {
  const faq = await getFAQ();
  // const products = await getProducts();
  
  return (
    <main className="">        
        <header className='catalog_header'>
          <Image className='catalog_header_img aspect-video w-[100%] h-[100vh] object-cover' src='/bg/catalog_header_background.png' width={1920} height={1080}/>
          <div className='container z-5 absolute translate-[-50%] translate-x-[-50%] left-[50%]'>
            <h1>КАТАЛОГ</h1>
            <p>Всё для вашего автомобиля - широкий выбор, надёжность и качество!</p>
          </div>
        </header>

        <section className='choose_category container m-auto'>
          
          <div className='section_header container m-auto'>
            <div className='header_line'></div>
            <h1>ВЫБОР КАТЕГОРИИ</h1>
          </div>
          
          <div className='catalog_categories'>
            
            <div className='catalog_category'>
              <Image src='/icons/catalog_png1.png' width={26} height={27}/>
              <p>Органайзеры</p>
            </div>
            
            <div className='catalog_category'>
              <Image src='/icons/catalog_png2.png' width={26} height={27}/>
              <p>Сумки</p>
            </div>
            
            <div className='catalog_category'>
              <Image src='/icons/catalog_png3.png' width={26} height={27}/>
              <p>Коврики для груза</p>
            </div>
            
            <div className='catalog_category'>
              <Image src='/icons/catalog_png4.png' width={26} height={27}/>
              <p>Матрасы</p>
            </div>
            
            <div className='catalog_category'>
              <Image src='/icons/catalog_png5.png' width={26} height={27}/>
              <p>Подстаканники</p>
            </div>

          </div>
            
          <div className='catalog_view_all'>
            <button className=''>
                Смотреть все категории
                <svg width="15" height="11" viewBox="0 0 15 11" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M9.30864 9.625L14 5.625M14 5.625L9.30864 1.625M14 5.625L0.518518 5.625" stroke="#95F35A" stroke-linecap="square"/>
                </svg>
            </button>
          </div>
          

        </section>
        
        <section className='section_filters'>
          
          <div className='filter_line_first container m-auto'></div>

          <div className='section_header container m-auto'>
            <div className='header_line'></div>
            <h1>ФИЛЬТРЫ</h1>
          </div>
          
          <div className='catalog_filters container m-auto'>
            <input className='catalog_filter' placeholder='Введите длину багажного автомобиля'></input>
            <input className='catalog_filter' placeholder='Введите ширину багажного автомобиля'></input>
            <button className='filter_button'>Применить фильтры</button>
          </div>
        
        </section>
        
        <Catalog />

        <FAQ data={faq}/>

        <section id='contacts' className='section_contact pb-[150px] relative'>
          <div className='container m-auto'>
            <div className='section_header'>
              <div className='section_header_inside'>
                <div className='header_line'></div>
                <h1>ОСТАЛИСЬ <span>ВОПРОСЫ</span>?</h1>
              </div>
              <p className='under_header_text'>Оставьте заявку и мы свяжемся с вами в ближайшее время, чтобы ответить на все ваши вопросы!</p>
            </div> 

            <div className='contact_main mt-[40px]'>
              <div className='contact_inputs'>
                <div className='inputs_up'>
                  <input placeholder='Ваше имя'></input>
                  <input placeholder='Ваш телефон'></input>
                  <input placeholder='Ваш e-mail'></input>
                </div>
                <div className='inputs_down'>
                  <input placeholder='Распишите ваши вопросы'></input>
                </div>
              </div>
              <div className='contact_text'>
                <a href=''><button className='text_button'>Отправить</button></a>
                <div className='text_link'>
                  <p>Нажимая на кнопку Отправить, я соглашаюсь с <a>офертой на обработку персональных данных.</a></p>
                </div>
              </div>
            </div>      
          </div> 

          <div className='absolute left-0 top-[200px] w-[50px] h-[300px] rounded-[513px] bg-[#95F35A] blur-[125px]'></div>
        </section>
    </main>
  )
}
