import CatalogPage from '@/windows/catalog/page'

export const metadata = {
  title: 'SleepBag Спальники-Органайзеры: Каталог',
  description: 'Generated by create next app',
}

export default async function Page() {
  return (
    <CatalogPage />
  )
}
