import CatalogPage from '@/pages/catalog/page'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function Page() {
  return (
    <CatalogPage />
  )
}
