import CartPage from '@/windows/personal/cart/page';

export const metadata = {
  title: 'SleepBag Спальники-Органайзеры: Корзина',
  description: 'Generated by create next app',
}

export default function Page() {
  return (
    <CartPage />
  )
}
