import CatalogPageSlug from '@/pages/catalog/[slug]/page'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Page({params}) {
    return (
        <CatalogPageSlug params={ params } />
    )
}
