import CatalogPageSlug from '@/windows/catalog/[slug]/page'

export const metadata = {
  title: 'SleepBag Спальники-Органайзеры: Продукт',
  description: 'Generated by create next app',
}

export default function Page({params}) {
    return (
      <CatalogPageSlug params={ params } />
    )
}
